### ISSUE TITLE
The NBA API downloads very very slow

### ISSUE THREAD

**Issue by Wheaties466** [klane/databall#354]
I know this is probably an improper use of an issue request but the NBA API downloads very slow. I'm not getting anything greater than 80 kBit/s. Would it be possible to put a test sqlite db in the repo? Maybe something like 2017-2018 player stats like you mention on the site. That would allow for getting up and running much quicker.

Thanks

**Comment by Wheaties466** [comment]
Looks like nba_py isn't a working implementation of the api.

this looks promising.

https://github.com/swar/nba_api

**Comment by klane** [comment]
Thanks for your interest @Wheaties466. I have plans to update the code with the long term goal of making a dynamic site to show predictions for the current day's games. If I remember correctly, the NBA API changed and [nba_py](https://github.com/seemethere/nba_py) was never updated. Thank you for pointing me to [nba_api](https://github.com/swar/nba_api). Have you experimented with it?

I like the idea of adding a small SQLite database so you can run the machine learning code without needing to scrape a bunch of data. I will likely add one when I revisit the project, but will also gladly accept a PR if you feel so inclined.

**Comment by Wheaties466** [comment]
@klane I am in the process of porting the project to nba_api but it looks like stats.nba.com depreciated a specific endpoint that you use to gather data. The gamelog endpoint. I unfortunately don't have any reference data to grab that same data from separate endpoints though so if you have any example data that would expedite my efforts.

**Comment by klane** [comment]
That's unfortunate the GameLog endpoint is deprecated. If I remember correctly, it provided an easy way to get game information for an entire season. I was able to dig up the SQLite database from a backup of my old machine, but I am hesitant to commit it if the schema needs to change. Is there another way you prefer to receive the database?

**Comment by Wheaties466** [comment]
@klane If you want to email me a google drive or dropbox(or similar service) link to the database I would appreciate it. My email should be in my profile now.

**Comment by klane** [comment]
@Wheaties466 That's awesome thank you for the help. I will try to send you a link sometime tonight PST.

I have not been able to commit much time to personal projects lately, but hope to work on a couple this summer. Are you interested in collaborating to further expand this project?

**Comment by Wheaties466** [comment]
Thanks! 

Yes I am interested in collaborating on this to expand the project! I am more of an ops guy so I don't write code for a living, point being that my background is in more back end work. But I did really like your vision for a future website and I am looking for something to work on to continue to expand my skillset.

So once I get the compatibility with the new api(which I have active issues open with as well) up and running, I would love to hear what you had in mind for an expansion.

**Comment by klane** [comment]
@Wheaties466 I sent you a link to the database. Let me know if you have any questions!

**Comment by Wheaties466** [comment]
@klane so in my fork i've got the database_builder working and is able to grab the same data but with the new API. I am having trouble figuring out how to calculate your advanced statics, luckily i've been able to figure out most everything else through the through documentation but I can't see to figure out how to calculate the advanced statistics.

I know it has to use betting_stats but I'm not quite sure how to call it properly. Any assistance would be appreciated.

**Comment by Wheaties466** [comment]
So I wasn’t able to get the games of endpoint working on the new api integration so I wrote a workaround that gathered the same day but with more api requests, then all of a sudden the gamelog endpoint started working for me. I know they have implemented banning IPs and have blacklisted hosting providers IPs, so it may have been that I finally got unbanned or that they didn’t have a specific endpoint working for days on end. But bottom line is I did end up getting it working with the new api. While I have been working with debugging/troubleshooting, I have installed requests-cache to make sure I don’t get banned from the api.

It looks like the html/css did change for the covers scrape and I was able to modify it to get the teams scrape to work but I’m a bit lost on how the games scape works done it keeps complaining about not having an argument. I’ve never used arguments with scapy so it may just take more trial and error.

**Comment by klane** [comment]
Wow that's awesome. Thanks for all the hard work!

**Comment by Wheaties466** [comment]
thanks! Do you have any immediate ideas on where you'd like to try to add features? I'm not incredibly familiar with it but it might be nice to try to do something with auto-sklearn to try to select the best model.

**Comment by klane** [comment]
I think the best place to start is with the data. The models had a difficult time achieving anything much better than random guessing against the spread. The Vegas odds makers are very good at their jobs.

I initially only used team stats for simplicity, but that doesn't account for injuries, midseason trades, or players resting. It would be better to use player stats and build up some sort of team strength for each game that accounts for the players actually in a given game. Ideally there is some historical injury reports we can leverage, but we can use the players that logged any minutes in a game as a proxy for a team's roster for that game.

Some other ideas I have are including a variable that indicates if a game is the second of a back-to-back or gives the game number within a given span (e.g. game 3 in a 5 day stretch). Another potential is to include referee information. Some refs are known for calling more fouls, which can inflate scoring because of the increased number of free throws. I looked for referee information a while back, but the only thing I found required scraping basketball reference for every single game, which I would prefer to avoid.

Does any of that make sense? Feel free to submit a PR that fixes the data acquisition and we can brainstorm the lowest hanging fruits.

**Comment by Wheaties466** [comment]
Yeah that makes complete sense and i think it would be helpful in analysis as well. I’ll submit the PR as soon as I have a chance to clean up some of the code.

**Comment by klane** [comment]
I didn't mean for you to close your PR. It appears that perhaps your local git config is not tied to your GitHub profile with all the commits by root. When you commit normally does it show up as coming from your profile? What are the contents of your .gitconfig file?

**Comment by Wheaties466** [comment]
I was committing on 2 different computers. It doesn't look like I have a .gitconfig file on either computer so it looks like it isn't setup.

I am trying to cherry pick a commit to limit the old commits. Still trying to get familiar with this whole process.

**Comment by klane** [comment]
No worries. If I may provide some advice it might be easier to understand the normal workflow by making a new fork. I am not the best at git myself and am unsure how best to remove the duplicate commits. Keep a copy of the local repo with your changes that you can reference, but delete the remote repo on GitHub. Then follow these steps:

1. Fork the repo on GitHub, which creates a new remote repo under your profile.
2. Clone your new repo locally. This can be accomplished in a variety of ways, but the most straightforward way is probably [`git clone <url>`](https://git-scm.com/docs/git-clone) on the command line.
3. It is common to create a new branch named according to its contribution (perhaps fix-data-scraping in this case), but that is not strictly required. You can create and checkout a new branch in one step with [`git checkout -b <branch-name>`](https://git-scm.com/docs/git-checkout#Documentation/git-checkout.txt--bltnewbranchgt).
4. Make local changes
5. Stage changes with [`git add <file>`](https://git-scm.com/docs/git-add)
6. Commit changes with [`git commit -m <message>`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--mltmsggt)
7. Repeat steps 4 through 6 as necessary
8. Push changes to the remote repo with [`git push`](https://git-scm.com/docs/git-push)
9. Navigate to your repo on GitHub
10. GitHub should detect that you have made changes to a fork and provide an option to create a pull request to the original repo.

**Comment by klane** [comment]
You can create a .gitconfig file in your root directory and populate it with [`git config`](https://git-scm.com/docs/git-config), or you can use your text editor of choice. At a minimum you should have:

```
[user]
  name = <name>
  email = <email>
```

You can take a look at my [gitconfig file](https://github.com/klane/dotfiles/blob/master/tools/git/.gitconfig) to see some of the things you can do.

**Comment by Wheaties466** [comment]
Thanks for the assistance with the git issues. The new PR is #384

**Comment by Wheaties466** [comment]
so it looks like officials that are calling the games later that night are announced at 9am EST here.

https://official.nba.com/referee-assignments/

we should be able to grab them from the [boxscoresummaryv2](https://github.com/swar/nba_api/blob/2326a9275a7859c8035a2a01342c11a3e54a73e7/docs/nba_api/stats/endpoints/boxscoresummaryv2.md)

I didn't find an api to get this from but it looks like this is easily iterate-able 

https://stats.nba.com/lineups/
https://stats.nba.com/js/data/dailylineups/2020/daily_lineups_20200309.json 
They apparently pull this from rotowire but this info is really nice to have. Would we need to have to calculate a score for a player to know their value to the team if they cannot play? Or is something like this already available?

**Comment by klane** [comment]
Good find! That's great information to have. They must have added officials since I looked at the API because I don't remember having that information available. The lineups will be even more helpful because it allows us to account for resting/injured/traded players when predicting future games.

There are a few different rating systems including WAR (Wins Above Replacement), which was pioneered in baseball where a value of 0 typically represents an average player that can be signed for the league minimum salary. [FiveThirtyEight](https://fivethirtyeight.com/) has a new player rating system called [RAPTOR](https://projects.fivethirtyeight.com/2020-nba-player-ratings/) that replaces their old CARMELO ratings. They put the data on [GitHub](https://github.com/fivethirtyeight/data/tree/master/nba-raptor) and there are a few other NBA-related folders in that repo that might be worth checking out. In grabbing the links just now I stumbled across their new repo for [player advanced metrics](https://github.com/fivethirtyeight/nba-player-advanced-metrics) that might also prove beneficial.

I believe FiveThirtyEight predicts games with team ratings calculated as the sum of their player ratings weighted by projected minutes played in that game. They also give a bonus to the home team to account for home court advantage. If a team rests one of their stars, their minutes get distributed amongst the rest of the team in some fashion. Bench players (i.e. less talented players) will see more minutes and their team's rating will go down for that game. I was only looking at team stats before and could not properly account for these situations.

**Comment by Wheaties466** [comment]
which would you like to focus on first? I have a decent amount of time in the evenings now that im pretty much home 24/7

**Comment by klane** [comment]
I am working on merging your pull request. It would be great if you could find a resource that provides projected minutes played for an upcoming game. We can use those minutes as weights for each player's rating and sum up the weighted player ratings to get an overall team rating. Perhaps we just use average minutes played that season, but that can take a while to stabilize and requires us to make some guesses at the beginning of a season.

Are you interested in using a different platform for discussion, such as Slack? Using issues for planning is probably not ideal.

**Comment by klane** [comment]
@Wheaties466 I made a few changes and merged the PR. Some of the changes were just syntax improvements since I wrote this when I was pretty new to Python. I also added some bare bones CI to start enforcing consistent style. It looks like there are still updates required to the scraper because it should grab all seasons starting with the season you pass in.

**Comment by Wheaties466** [comment]
I'll take a look at the scraper again now that I have a better understanding of how we want it to work.

**Comment by klane** [comment]
Hey @Wheaties466 does the scraper make sense? I remembered where the JSON in the game spider came from as I went through the code again. I stored the output of the team spider to a JSON file and used that as the input to the game spider as outlined below. I will add that along with some additional information to the README.

```
scrapy crawl teams -o teams.json
scrapy crawl games -a teams=teams.json
```
